{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi-registry.fullname" . }}
  labels:
    {{- include "nifi-registry.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    {{- range $name, $number := $.Values.ports }}
    - name: {{ $name }}
      port: {{ $number }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "nifi-registry.selectorLabels" . | nindent 4 }}
{{- end }}